### ISSUE TITLE
3.0 Roadmap

### ISSUE THREAD

**Issue by adamgruber** [adamgruber/mochawesome-report-generator#57]
Tasks to complete for 3.0 release

- [x] Improve perceived performance
  - [x] Render stats / page loader before report body (https://github.com/adamgruber/mochawesome-report-generator/pull/54)
  - ~[Investigate filtering tests via CSS](https://github.com/adamgruber/mochawesome-report-generator/issues/58)~
  - [x] Make toggles more responsive, no lag when clicking (https://github.com/adamgruber/mochawesome-report-generator/pull/64)
  - [x] Display loader as needed when rendering large number of tests (https://github.com/adamgruber/mochawesome-report-generator/pull/64)
- [x] Update to new trimmed data structure (https://github.com/adamgruber/mochawesome-report-generator/pull/43)
- [x] Refactor CSS to use flexbox (https://github.com/adamgruber/mochawesome-report-generator/pull/46)
- [x] Optimize component renders (https://github.com/adamgruber/mochawesome-report-generator/pull/51)
- [x] Improve functional tests (https://github.com/adamgruber/mochawesome-report-generator/pull/52)
- [x] [Pull in options handling from reporter](https://github.com/adamgruber/mochawesome/issues/193) (https://github.com/adamgruber/mochawesome-report-generator/pull/59)
 (https://github.com/adamgruber/mochawesome/pull/194)
- [x] Update dependencies (https://github.com/adamgruber/mochawesome-report-generator/pull/68)
- [x] Update documentation (https://github.com/adamgruber/mochawesome-report-generator/pull/70)

**Comment by larryg01** [comment]
I love this reporter over Cucumber-html-reporter, do you have any plans to make this compatible with cucumber for reporting?

**Comment by adamgruber** [comment]
@larryg01 Thanks for the feedback. I'd actually never heard of Cucumber before and unfortunately I don't have any plans right now to expand compatibility beyond mocha / mochawesome. That said it shouldn't be too difficult to implement as long as you can transform the Cucumber test output into the format that this reporter expects.

**Comment by adamgruber** [comment]
3.0.0 has been released
